Add domain wide node selector
oracle/weblogic-toolkit-ui pull request #152
Opened 2022-08-10 19:05 UTC by CarolynRountree

Fixes Jira #356

Add node selector to domain wide server pod in advanced section

2022-08-10 19:16 UTC, rakillen commented on electron/app/locales/en/webui.json
> +  "domain-design-node-selector-label": "Kubernetes node selector",
Adjacent `*-label` entries are capitalized, should this be "Kubernetes Node Selector" ?

2022-08-10 19:20 UTC, rakillen approved these changes

2022-08-10 19:38 UTC, robertpatrick requested changes

2022-08-10 19:38 UTC, robertpatrick commented on webui/src/js/utils/k8s-domain-resource-generator.js
> +      const serverPod = _getServerPod(getJavaOptionsForCluster(cluster), getUserMemArgsForCluster(cluster), getKubernetesResourcesForCluster(cluster), null) || {};
If you remove the ugly `null` argument, then the receiving function will simply get `undefined` for the argument value.  If it makes you feel better, you can add a default value for that argument in the function argument list.  That is a more JavaScript-way of doing this.

```
const serverPod = _getServerPod(getJavaOptionsForCluster(cluster), getUserMemArgsForCluster(cluster), getKubernetesResourcesForCluster(cluster)) || {};

...
function _getServerPod(javaOptions, userMemArgs, resources, nodeSelector = null) {
...

```

2022-08-10 19:38 UTC, robertpatrick commented on webui/src/js/utils/k8s-domain-resource-generator.js
>        return Object.keys(serverPod).length > 0 ? serverPod : null;
You do realize that you have committed code with merge conflict markers in it, right?

2022-08-10 19:38 UTC, robertpatrick commented on webui/src/js/views/domain-design-view.html
> +      </oj-input-text>
How is this supposed to work?

I would have assumed that the user can tell you both the label name and the label value that they want to use as the node selector?  It seems like you are assuming a label name but it isn't clear what that is...

2022-09-08 19:39 UTC, robertpatrick commented
This will be added with the Verrazzano support that is coming in the next week or so.

2022-09-08 19:39 UTC, closed without merging